apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webdev
          image: docker.io/library/sushil3710/gitachatbot:v1
          ports:
            - containerPort: 8051