name: Build and Deploy Chatbot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Build Docker Image
        run: |
          docker build -t chatbot-image .
        shell: bash

      - name: Log into Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: docker tag chatbot-image:latest aryax9/chatbot-llama2-gitascript:latest 
      
      - name: Push to Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/chatbot-llama2-gitascript:latest
